name: ci

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd infrastructure/
            sudo docker-compose stop
            sudo docker-compose down
            sudo docker rm -f $(sudo docker ps -aq)
            git pull origin
            sudo docker-compose up -d